### ISSUE TITLE
foundations/README.md does not exist

### ISSUE THREAD

**Issue by levaid** [facebookresearch/open_lth#1]
Hey!

I've started using this repository, but there is a README file missing.

You state in 2.3 that:
To learn about adding more experimental workflows, see **foundations/README.md**.

It does not exist, and I am having a hard time figuring out how branches work.

**Comment by jfrankle** [comment]
Hi there -

I'm so sorry I left the hanging reference to `foundations/README.md` in there. Instead, I added that content in Section 4. For learning more about adding branches, see Section 4 as well.

Jonathan
