### ISSUE TITLE
ResNet num params

### ISSUE THREAD

**Issue by zankner** [facebookresearch/open_lth#7]
Hey, thanks for this repo. Your work on the LTH is really awesome!

I had a question about the resnet18 architecture provided. I noticed that the model was running a lot faster than other resnet18 models, so I printed the number of trainable parameters and noticed that for `cifar_resnet_18` the number of parameters was 272474, whereas the resnet18 model from pytorch is around 11 million parameters. I was wondering if you could provide the naming schema that would return the typical 11 million parameter model?

Thanks

**Comment by jfrankle** [comment]
The resnet18 from PyTorch is imagenet_resnet_18 in OpenLTH.

**Comment by zankner** [comment]
Thanks!
